"""empty message

Revision ID: 70c8d44be996
Revises: 73b8d98d6e88
Create Date: 2024-05-18 19:13:55.782217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70c8d44be996'
down_revision = '73b8d98d6e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.Enum('buy', 'sell', name='order_types'), nullable=False))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'matched', 'closed', name='order_statuses'),
               nullable=False)
        batch_op.drop_column('order_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_types', postgresql.ENUM('buy', 'sell', name='order_types'), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'matched', 'closed', name='order_statuses'),
               nullable=True)
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###
